In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [3]:
df


text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [4]:
# !pip install scikit-learn


In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [6]:
bow=cv.fit_transform(df['text'])

In [8]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}

In [12]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())


[[1 0 1 1 0]]
[[2 0 0 1 0]]
[[0 1 1 0 1]]


In [16]:
cv.transform(['Campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 1]], dtype=int64)

# N-Gram



In [30]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [39]:
cv=CountVectorizer(ngram_range=(1,2))

In [40]:
bow=cv.fit_transform(df['text'])

In [41]:
cv.vocabulary_

{'people': 4,
 'watch': 7,
 'campusx': 0,
 'people watch': 5,
 'watch campusx': 8,
 'campusx watch': 1,
 'write': 9,
 'comment': 3,
 'people write': 6,
 'write comment': 10,
 'campusx write': 2}

In [42]:
bow[0].toarray()

array([[1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0]], dtype=int64)

In [43]:

print(bow[0].toarray())

[[1 0 0 0 1 1 0 1 1 0 0]]


In [44]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [45]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [46]:
print(tfidf.idf_)

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]


# assignment

In [63]:
df=pd.read_csv('imdb/imdb.csv')

In [64]:
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [65]:
df['review'].head(10)

0    One of the other reviewers has mentioned that ...
1    A wonderful little production. <br /><br />The...
2    I thought this was a wonderful way to spend ti...
3    Basically there's a family where a little boy ...
4    Petter Mattei's "Love in the Time of Money" is...
5    Probably my all-time favorite movie, a story o...
6    I sure would like to see a resurrection of a u...
7    This show was an amazing, fresh & innovative i...
8    Encouraged by the positive comments about this...
9    If you like original gut wrenching laughter yo...
Name: review, dtype: object

In [66]:
import re

def rem_tags(text):
    clean_text=re.sub(r'<.*?>','',text)
    return clean_text
def rm_punc(text):
    clean_text=[]
    for x in text:
        if x in punct:
            pass
        else:
            clean_text.append(x)
    return ''.join(clean_text)
            

import string
punct=string.punctuation
print(punct)

df['review']=df['review'].apply(rem_tags)

df

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [75]:
def remove_punctuation(text):
    # Use re.sub to replace all punctuation characters with an empty string
    clean_text=re.sub(f"[{re.escape(string.punctuation)}]", '', text)
    return clean_text.lower()

In [76]:
df['review']=df['review'].apply(remove_punctuation)

In [77]:
df

review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [81]:
words={}

def count_word(text):
    for x in text.split(' '):
        if x in words:
            words[x]+=1
        else:
            words[x]=1
    return text
df['review']=df['review'].apply(count_word)


In [118]:
# words

In [119]:
len(words)

223907

In [86]:
words_df=pd.DataFrame({'word':words.keys(),"times":words.values()})

In [87]:
words_df 

word   times
0                    one   50358
1                     of  288060
2                    the  650537
3                  other   17773
4              reviewers     500
...                  ...     ...
223902  horriblecatwoman       1
223903         theirsall       1
223904        originalif       1
223905            goodat       1
223906         yosemitei       1

[223907 rows x 2 columns]

In [91]:
total_words=words_df['times'].sum()
unique_words=words_df.size

In [92]:

print(total_words)
print(unique_words)

11355214
447814


In [93]:
words_df

word   times
0                    one   50358
1                     of  288060
2                    the  650537
3                  other   17773
4              reviewers     500
...                  ...     ...
223902  horriblecatwoman       1
223903         theirsall       1
223904        originalif       1
223905            goodat       1
223906         yosemitei       1

[223907 rows x 2 columns]

In [96]:
df_encoded=pd.get_dummies(words_df,columns=['word'],sparse=True)

In [97]:
df_encoded.shape

(223907, 223908)

In [112]:
from sklearn.feature_extraction.text import CountVectorizer
cv1=CountVectorizer()

In [113]:
bow=cv1.fit_transform(df['review'])

In [114]:
len(cv1.vocabulary_)

221438

In [115]:
cv=CountVectorizer(ngram_range=(3,3))

In [116]:
bon=cv.fit_transform(df['review'])

In [117]:
len(cv.vocabulary_)

6702899